# This is a basic workflow to help you get started with Actions

name: Cypress Tests

# Controls when the workflow will run
on: [push]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
